import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { AuthProvider } from "@/contexts/AuthProvider";
import { PostsProvider } from "@/contexts/PostsProvider";
import DeleteDialog from "@/components/dialog/DeleteDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AuthProvider>
          <PostsProvider>
            <div className="flex flex-col h-screen">{children}</div>
            <DeleteDialog />
          </PostsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
