import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { UserProvider } from "@/contexts/UserProvider";
import { PostsProvider } from "@/contexts/PostsProvider";
import { DrawerProvider } from "@/contexts/DrawerProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <UserProvider>
          <PostsProvider>
            <DrawerProvider>
              <div className="flex flex-col h-screen">{children}</div>
            </DrawerProvider>
          </PostsProvider>
        </UserProvider>
      </body>
    </html>
  );
}
